### ISSUE TITLE
OldExplorer Starts Slowly

### ISSUE THREAD

**Issue by ShaunToole** [LesFerch/OldExplorer#6] opened 2024-11-13 16:31 UTC
First, thanks for the wonderful solution OldExplorer provides. 

I run OldExplorer from a Win11 taskbar. There is a long lag before OldExplorer opens the first time I use the shortcut in a Windows session. This delay occurs whether I am opening Favorites, Home, or any other location. Is there a way to help the performance of OldExplorer?  

The shortcut has the Target: "C:\Users\shaun\Downloads\Old Explorer\OldExplorer\OldExplorer.exe" Favorites

On the Shortcut Properties, I have checked "Register this program for restart." Would this affect the first opening, subsequent opening, or any of those events?

Thanks again!

**Comment by LesFerch** [comment] 2024-11-13 17:33
Checking "Register this program for restart." would have no effect. That's for programs that support ARR which I think is a feature for recovering user data on restart. It's not applicable here.

Anyhow, I see no delays launching OldExplorer even after just restarting. You may have to do some trial and error testing to determine what variables are involved. Try starting up in Safe Mode and see if that makes a difference.

If you have something installed that patches Explorer on the fly, such as QTTabBar, that might make a difference. The Safe Mode test should indicate if the lag is caused by another app.

**Comment by ShaunToole** [comment] 2024-11-13 17:51
Thanks for the reply and the info. And for coming up with OldExplorer.

**Comment by LesFerch** [comment] 2024-11-13 18:38
Try moving it out of your downloads folder to another location such as C:\Tools\OldExplorer\. Maybe your AV software is rescanning files in Downloads.

**Comment by ShaunToole** [comment] 2024-11-14 14:39
This morning it ran much faster on the first execution. I think the reboot helped. Good idea about the folder location. I will give that a try.

**Comment by ShaunToole** [comment] 2024-11-14 15:23
I may have spoken too soon about the improved performance, and moving the exe to C:\Tools\OldExplorer did not dramatically improve performance. 

But even with the delayed opening, the restored functionality is worth the wait. 

I will continue to monitor.

**Comment by LesFerch** [comment] 2024-11-14 15:28
Please test it in Safe Mode. That should tell us if other software is causing the delay.

Hold Shift while selecting Restart
Troubleshoot
Advanced Options
Startup Settings
Restart
4) Enable Safe Mode

**Comment by ShaunToole** [comment] 2024-11-15 18:20
Thanks for your patience while I try a couple of experiments and collect results. The results are not too enlightening, but it will be interesting to see what you make of them. 

Before today, I had found that opening OldExplorer with “This PC” as a parameter worked very well when booted into Windows 11 normally, but the parameter Home a “long time” to finish opening Explorer. I didn’t time the delay, but my guess is it required 15 to 30 seconds. 

In Safe Mode with Networking, using either parameter gave very fast results. Explorer opened quickly. 

Back in Windows 11 normal mode, the results were the same as in Safe Mode – using either parameter did not make a difference in performance. 

I will continue to monitor and post back if I have some more performance issues, noting the parameter and any other differences between good response times and slow.

**Comment by LesFerch** [comment] 2024-11-16 04:08
General strangeness there. I was thinking that the links that are currently in your Home might be a factor, especially if a network drive and/or OneDrive is involved, but if it's now fast, then I dunno.

I don't know if it's related, but I've observed that killing and restarting Explorer on Windows 11 sometimes takes 15 to 30 seconds (on a very fast computer) for no apparent reason. I've never seen that issue on Windows 10.

**Comment by ShaunToole** [comment] 2024-11-16 13:11
Right! My PC is “very fast” - Core i7 processor, 32 GB ram, M.2 SSD, etc. I
resisted Windows 11 for a long while just to maintain a stable and familiar
working environment. Why fix what ain’t broke? So, these revisions and
performance “improvements” are making it more likely that I will roll back
to Windows 10 and give MSFT another year to improve their improvements.

Thank you again for your support and contributions to this community.

**Comment by LesFerch** [comment] 2024-11-25 13:24
I'm closing this issue since it's a Windows 11 quirk and not a bug in OldExplorer.

**Closed as not planned by LesFerch** 2024-11-25 13:24 UTC

**Comment by ShaunToole** [comment] 2024-11-25 14:39
Your input was helpful. Thanks. 

I have since seen that OldExplorer opens quickly when the option "This PC" is used, but other options are slow. The network drives and possibly creating previews of AV files may be slowing down the others. I will post again if I see a solution to those issues.
